---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

# Mallona et al. NAR 2020


Data from: https://doi.org/10.1093/nar/gkaa1168

<!-- #region tags=[] -->
### initialize definitions
<!-- #endregion -->

```{r}
suppressMessages(suppressWarnings(source(here::here("code/init.R"))))
```

```{r}
md_baubec <- tibble::tribble(
    ~name, ~track,
    "active_3a", "Mallona_NAR_2020.HA36_TKO_DNMT3A2_r2",
    "active_3b", "Mallona_NAR_2020.HA36_TKO_DNMT3B1_r2"
)
md_baubec
```

```{r}
baubec_meth_all <- misha.ext::gextract_meth(tracks = md_baubec$track, names =  md_baubec$name, extract_meth_calls = TRUE) %cache_df% here("output/baubec_meth_all.tsv") %>% as_tibble()
```

```{r}
baubec_meth_plus <- misha.ext::gextract_meth(tracks = paste0(md_baubec$track, "_plus"), names =  md_baubec$name, extract_meth_calls = TRUE) %cache_df% here("output/baubec_meth_plus.tsv") %>% as_tibble()
baubec_meth_minus <- misha.ext::gextract_meth(tracks = paste0(md_baubec$track, "_minus"), names =  md_baubec$name, extract_meth_calls = TRUE) %cache_df% here("output/baubec_meth_minus.tsv") %>% as_tibble()
```

```{r}
baubec_meth_all %>% filter(active_3a.cov > 0 | active_3b.cov > 0) %>% nrow()
baubec_meth_plus %>% filter(active_3a.cov > 0 | active_3b.cov > 0) %>% nrow()
baubec_meth_minus %>% filter(active_3a.cov > 0 | active_3b.cov > 0) %>% nrow()
```

```{r}
summary(baubec_meth_all$active_3a.cov[baubec_meth_all$active_3a.cov > 0])
scales::comma(sum(baubec_meth_all$active_3a.cov > 0))

summary(baubec_meth_plus$active_3a.cov[baubec_meth_plus$active_3a.cov > 0])
scales::comma(sum(baubec_meth_plus$active_3a.cov > 0))

summary(baubec_meth_minus$active_3a.cov[baubec_meth_minus$active_3a.cov > 0])
scales::comma(sum(baubec_meth_minus$active_3a.cov > 0))
```

```{r}
summary(baubec_meth_all$active_3b.cov[baubec_meth_all$active_3b.cov > 0])
scales::comma(sum(baubec_meth_all$active_3b.cov > 0))

summary(baubec_meth_plus$active_3b.cov[baubec_meth_plus$active_3b.cov > 0])
scales::comma(sum(baubec_meth_plus$active_3b.cov > 0))

summary(baubec_meth_minus$active_3b.cov[baubec_meth_minus$active_3b.cov > 0])
scales::comma(sum(baubec_meth_minus$active_3b.cov > 0))
```

```{r}
baubec_meth_cov <- baubec_meth_all %>% filter(active_3a.cov >= 10, active_3b.cov >= 10) 
nrow(baubec_meth_cov)
```

```{r}
baubec_meth_plus_cov <- baubec_meth_plus %>% filter(active_3a.cov >= 10, active_3b.cov >= 10) 
nrow(baubec_meth_plus_cov)
```

```{r}
baubec_meth_minus_cov <- baubec_meth_minus %>% filter(active_3a.cov >= 10, active_3b.cov >= 10) 
nrow(baubec_meth_minus_cov)
```

```{r}
esc_wgbs <- misha.ext::gextract_meth("schuebler.wgbs.esc.sum", intervals=gintervals.all(), names="esc") %>% 
    filter(esc.cov >= 7) %>% 
    select(-intervalID) %cache_df% 
    here("data/schuebler_esc_wgbs.tsv") %>% 
    as_tibble()
```

```{r}
filter_low_esc_meth <- function(df, esc_wgbs){
    df %>% inner_join(esc_wgbs %>% select(chrom, start, end, esc) %>% filter(esc >= 0.05))
}
```

## Model ES

```{r}
m_bau_plus <- baubec_meth_plus_cov %>% 
    filter_low_esc_meth(esc_wgbs)
m_bau_minus <- baubec_meth_minus_cov %>% 
    filter_low_esc_meth(esc_wgbs) 

scales::comma(nrow(m_bau_plus))
scales::comma(nrow(m_bau_minus))
```

```{r}
intervs_all_plus <- m_bau_plus %>% select(chrom, start, end)
intervs_all_minus <- m_bau_minus %>% select(chrom, start, end)
```

```{r}
seq_df_plus <- get_seq_df(intervs_all_plus, flank_bp = 5)
seq_df_minus <- get_seq_df(intervs_all_minus, strand = -1, flank_bp = 5)
```

```{r}
seq_df_wide_plus <- seq_df_to_wide(seq_df_plus, flank_bp = 5)
seq_df_wide_minus <- seq_df_to_wide(seq_df_minus, flank_bp = 5)
```

```{r}
head(m_bau_plus)
```

```{r}
model_ab_bau_plus_A <- gen_seq_model(seq_df_wide_plus, m_bau_plus, active_3a) %cache_rds% here("output/baubec_plus_a_dinuc_model_5bp.rds")
model_ab_bau_plus_B <- gen_seq_model(seq_df_wide_plus, m_bau_plus, active_3b) %cache_rds% here("output/baubec_plus_b_dinuc_model_5bp.rds")

model_ab_bau_minus_A <- gen_seq_model(seq_df_wide_minus, m_bau_minus, active_3a) %cache_rds% here("output/baubec_plus_a_dinuc_model_5bp.rds")
model_ab_bau_minus_B <- gen_seq_model(seq_df_wide_minus, m_bau_minus, active_3b) %cache_rds% here("output/baubec_plus_b_dinuc_model_5bp.rds")
```

```{r}
options(repr.plot.width = 12, repr.plot.height = 6)
bandwidth <- 0.08
point_size <- 0.001
p_a <- tibble(pred = model_ab_bau_plus_A$pred, y = model_ab_bau_plus_A$y) %>% 
    mutate(col = densCols(., bandwidth=0.06,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=pred, y=y, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() +         
        xlab("Dinucleotide combined model") + 
        ylab("Meth (3a-/-)") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("R^2 = {cor}", cor = round(cor(model_ab_bau_plus_A$pred, model_ab_bau_plus_A$y)^2, digits=2))) + 
        theme(plot.subtitle = ggtext::element_markdown())

p_b <- tibble(pred = model_ab_bau_plus_B$pred, y = model_ab_bau_plus_B$y) %>% 
    mutate(col = densCols(., bandwidth=0.06,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=pred, y=y, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() + 
        xlab("Dinucleotide combined model") + 
        ylab("Meth (3b-/-)") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("R^2 = {cor}", cor = round(cor(model_ab_bau_plus_B$pred, model_ab_bau_plus_B$y)^2, digits=2))) + 
        theme(plot.subtitle = ggtext::element_markdown())

p_a + p_b
```

```{r}
coef_df_A <- get_coef_df(model_ab_bau_plus_A)
coef_df_B <- get_coef_df(model_ab_bau_plus_B)
```

### Figure 5B,C

```{r tags=c()}
options(repr.plot.width = 12, repr.plot.height = 6)
p_a <- coef_df_A %>% 
    ggplot(aes(x=pos, y=dinuc, fill=coefficient)) + 
        geom_tile() + 
        scale_fill_gradient2(low = "darkblue", high = "darkred", mid = "white", midpoint = 0, na.value="white") + 
        theme_minimal() + 
        ylab("Dinucleotide") + 
        xlab("Position") + 
        ggtitle("A")
p_b <- coef_df_B %>% 
    ggplot(aes(x=pos, y=dinuc, fill=coefficient)) + 
        geom_tile() + 
        scale_fill_gradient2(low = "darkblue", high = "darkred", mid = "white", midpoint = 0, na.value="white") + 
        theme_minimal() + 
        ylab("Dinucleotide") + 
        xlab("Position") + 
        ggtitle("B")
p_a + p_b
```

```{r}
model_ab <- readr::read_rds(here("output/ab_dinuc_model_5bp.rds"))
model_a <- readr::read_rds(here("output/a_dinuc_model_5bp.rds"))
model_b <- readr::read_rds(here("output/b_dinuc_model_5bp.rds"))
```

```{r}
all_cpgs <- gintervals.load("intervs.global.seq_CG")
```

```{r}
intercept_A <- coef(model_ab_bau_plus_A$fit_cv, s = "lambda.min")[1, ]
intercept_B <- coef(model_ab_bau_plus_B$fit_cv, s = "lambda.min")[1, ]
```

```{r}
coef_mat_A <- coef_df_to_matrix(coef_df_A %>% select(pos, dinuc, coefficient), model_ab, intercept=intercept_A) %cache_rds% here("output/coef_A_mat.rds")
coef_mat_B <- coef_df_to_matrix(coef_df_B %>% select(pos, dinuc, coefficient), model_ab, intercept=intercept_B) %cache_rds% here("output/coef_B_mat.rds")
```

```{r}
res <- compute_interval_model_mat_score_parallel(all_cpgs, model_ab, coef_mat_A, coef_mat_A, coef_mat_B) %cache_df% here("output/baubec_model_vs_ours_not_sym.tsv") %>% as_tibble()
```

### Figure 5D

```{r}
a_limits <- c(-0.1,0.5)
a_bins <- seq(-0.1, 0.5, length.out = 30)
b_limits <- c(-0.05,0.2)
b_bins <- seq(-0.05, 0.2, length.out = 30)
```

```{r}
cols <- colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred"))
options(repr.plot.width = 7, repr.plot.height = 7)
smoothScatter(
    res$score_a_plus, 
    res$score_a_minus,     
    xlab="+", 
    ylab = "-",     
    xlim = a_limits, 
    ylim = a_limits, 
    colramp = cols)
abline(v = a_bins, h = a_bins, col=alpha(rgb(0,0,0), 0.1))
abline(a = 0, b = 1, lty=5)
```

### Figure 5E

```{r}
options(repr.plot.width = 7, repr.plot.height = 7)
smoothScatter(
    res$score_b_plus, 
    res$score_b_minus,     
    xlab="+", 
    ylab = "-",     
    xlim = b_limits, 
    ylim = b_limits,
    colramp = cols)
abline(v = b_bins, h = b_bins, col=alpha(rgb(0,0,0), 0.1))
abline(a = 0, b = 1, lty=5)
```

```{r}
df <- {
    df_wt <- tracks_key  %>% filter(day == "d5") %>% filter(line == "wt")
    df_ko3a <- tracks_key  %>% filter(day == "d5") %>% filter(line == "ko3a")
    df_ko3b <- tracks_key  %>% filter(day == "d5") %>% filter(line == "ko3b")
    df_ab_bulk <- extract_meth_annot(c(
        df_wt$track_name, 
        df_ko3a$track_name, 
        df_ko3b$track_name), 
        names = c(df_wt$name, df_ko3a$name, df_ko3b$name), d_expand = 250, extract_meth_calls = TRUE)
    df <- df_ab_bulk %>% select(chrom, start, end, d_exon:gc_cont)
    df$wt.meth <- rowSums(df_ab_bulk[, paste0(df_wt$name, ".meth")], na.rm=TRUE)
    df$wt.cov <- rowSums(df_ab_bulk[, paste0(df_wt$name, ".cov")], na.rm=TRUE)

    df$ko3a.meth <- rowSums(df_ab_bulk[, paste0(df_ko3a$name, ".meth")], na.rm=TRUE)
    df$ko3a.cov <- rowSums(df_ab_bulk[, paste0(df_ko3a$name, ".cov")], na.rm=TRUE)

    df$ko3b.meth <- rowSums(df_ab_bulk[, paste0(df_ko3b$name, ".meth")], na.rm=TRUE)
    df$ko3b.cov <- rowSums(df_ab_bulk[, paste0(df_ko3b$name, ".cov")], na.rm=TRUE)

    df$ko3a <- df$ko3a.meth / df$ko3a.cov
    df$wt <- df$wt.meth / df$wt.cov
    df$ko3b <- df$ko3b.meth / df$ko3b.cov
    df    
} %cache_df% here("output/ab_diff_d5_bulk.tsv") %>% as_tibble()
```

We take only regions that are well covered and add a `diff` column with `3a(-/-) - 3b(-/-)`

```{r}
min_cov <- 50
df_diff <- {
        df_diff <- df %>% filter(ko3a.cov >= min_cov, ko3b.cov >= min_cov, wt.cov >= min_cov) %>% mutate(diff = ko3a - ko3b)
        df_diff <- df_diff %>% gintervals.neighbors1("intervs.global.tss") %>% select(chrom:diff, geneSymbol, dist)
        df_diff
} %cache_df%  here("output/ab_diff_d5_bulk_diff.tsv") %>% as_tibble()
```

```{r}
head(df_diff)
```

```{r}
meth_df_meeb <- df_diff %>% left_join(res)
```

```{r}
meth_df_meeb <- meth_df_meeb %>% rename(mA = ko3a, mB = ko3b)
```

```{r}
meth_df_meeb_f <- meth_df_meeb %>% 
    filter(abs(d_tss) >= 2000) %>% 
    filter_low_esc_meth(esc_wgbs) %>% 
    gintervals.neighbors1(get_all_enhancers()) %>% 
    filter(dist != 0) %>% 
    select(-(chrom1:end1))
dim(meth_df_meeb_f)
```

```{r}
meth_df_meeb_f %>% colnames()
```

### Figure 5F,G

```{r}
meth_df_meeb_d4 <- calc_eb_day0_to_day4_cpg_meth(min_cov = 10, max_na  = 5) %>% 
    rename(mA = d4_3a, mB = d4_3b) %>% 
    inner_join(fread(here("output/ebd_day1_to_day4_cpg_meth_mat.tsv")) %>% select(chrom, start, end)) %>% 
    left_join(res)
```

```{r}
df_A <- meth_df_meeb_d4 %>%
        mutate(score_plus = cut(score_a_plus, a_bins)) %>%
        mutate(score_minus = cut(score_a_minus, a_bins)) %>%
        group_by(score_plus, score_minus) %>%
        summarise(mB = mean(mB, na.rm=TRUE)) %>%         
        filter(!is.na(score_plus), !is.na(score_minus)) %>% 
        tidyr::complete(fill=list(mB = NA))  %>% 
    arrange(score_plus) %>%
    group_by(score_minus) %>%
    mutate(mB = zoo::rollapply(mB, FUN = function(x) mean(x, na.rm=TRUE), width=4, fill=NA)) %>%
    arrange(score_minus) %>%
    group_by(score_plus) %>%    
    mutate(mB = zoo::rollapply(mB, FUN = function(x) mean(x, na.rm=TRUE), width=4, fill=NA)) %>%
    na.omit()                       
```

```{r tags=c()}
df_B <- meth_df_meeb_d4 %>%
        mutate(score_plus = cut(score_b_plus, b_bins)) %>%
        mutate(score_minus = cut(score_b_minus, b_bins)) %>%
        group_by(score_plus, score_minus) %>%
        summarise(mA = mean(mA, na.rm=TRUE)) %>%         
        filter(!is.na(score_plus), !is.na(score_minus)) %>% 
        tidyr::complete(fill=list(mA = NA)) %>% 
    arrange(score_plus) %>%
    group_by(score_minus) %>%
    mutate(mA = zoo::rollapply(mA, FUN = function(x) mean(x, na.rm=TRUE), width=4, fill=NA)) %>%
    arrange(score_minus) %>%
    group_by(score_plus) %>%    
    mutate(mA = zoo::rollapply(mA, FUN = function(x) mean(x, na.rm=TRUE), width=4, fill=NA)) %>%
    na.omit()
```

```{r}
limits <- c(min(df_A$mB, df_B$mA), max(df_A$mB, df_B$mA))
limits
```

```{r}
options(repr.plot.width = 7, repr.plot.height = 7)
colors <- viridis::viridis(30, option = "A")

p_A <- df_A %>% 
    ggplot(aes(x=score_plus, y=score_minus, fill=mB)) + 
            geom_tile() + 
            scale_fill_gradientn(colors=colors, limits=limits) + 
            vertical_labs() + 
            scale_x_discrete(drop=FALSE) + 
            scale_y_discrete(drop=FALSE) + 
            xlab("+ strand A model") + 
            ylab("- strand A model") + 
            ggtitle("MEEB 3B-/- methylation day 4") + 
            theme(axis.ticks.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank())
p_B <- df_B %>% 
    ggplot(aes(x=score_plus, y=score_minus, fill=mA)) + 
            geom_tile() + 
            scale_fill_gradientn(colors=colors, limits=limits) + 
            vertical_labs() + 
            scale_x_discrete(drop=FALSE) + 
            scale_y_discrete(drop=FALSE) + 
            xlab("+ strand B model") + 
            ylab("- strand B model") + 
            ggtitle("MEEB 3A-/- methylation Day 4") + 
            theme(axis.ticks.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank())

p_A 
p_B
```

#### Predict MEEB using strands

```{r}
meth_df_meeb <- fread(here("output/ebd_day1_to_day4_cpg_meth_mat.tsv")) %>% left_join(res)
```

```{r}
feats_mat_comb_df <- meth_df_meeb %>% 
    inner_join(meth_df_meeb_d4 %>% select(chrom, start, end)) %>% 
    mutate(score_max_a = pmax(score_a_plus, score_a_minus)) %>% 
    mutate(score_max_b = pmax(score_b_plus, score_b_minus)) %>% 
    select(chrom, start, end, score_a_plus, score_a_minus, score_b_plus, score_b_minus, score_max_a, score_max_b, dAB) %>% 
    filter(!is.na(dAB))

feats_mat_comb <- feats_mat_comb_df %>% 
    select(-(chrom:end)) %>% 
    as.matrix()

feats_mat_comb %>% dim
```

```{r tags=c()}
library(xgboost)
dtrain <- xgb.DMatrix(feats_mat_comb[, -7], label=feats_mat_comb[, 7])

xgb_params <- readr::read_rds(here("data/xgb_params.rds"))

xgbcv <- xgb.cv(params = xgb_params$params, data = dtrain, nrounds = xgb_params$nrounds, nfold = 10, prediction = TRUE)

xgbtrain <- xgb.train(params = xgb_params$params, data = dtrain, nrounds = xgb_params$nrounds)

feats_mat_comb_df <- feats_mat_comb_df %>% 
    mutate(pred = xgbcv$pred)

```

Predict all CpGs: 

```{r}
d_all <- xgb.DMatrix(res %>% 
    mutate(score_max_a = pmax(score_a_plus, score_a_minus)) %>% 
    mutate(score_max_b = pmax(score_b_plus, score_b_minus)) %>%     
    select(score_a_plus, score_a_minus, score_b_plus, score_b_minus, score_max_a, score_max_b) %>% 
    as.matrix())
res <- res %>%
        mutate(comb_score = predict(xgbtrain, d_all))        
```

```{r}
shap_contrib <- predict(xgbtrain, dtrain, predcontrib=TRUE, approxcontrib=TRUE) 
shap_contrib %>% head()
```

```{r}
colMeans(abs(shap_contrib)) 
```

### Figure 5H

```{r}
p_shap <- colMeans(abs(shap_contrib)) %>% 
    set_names(c("A+", "A-", "B+", "B-", "max(A)", "max(B)", "BIAS")) %>% 
    enframe() %>% 
    arrange(value) %>%
    filter(name != "BIAS") %>%      
    ggplot(aes(x=reorder(name, value), y=value)) + geom_col() + coord_flip() + ylab("Mean Shapley Value") + xlab("Feature")

p_shap
```

```{r}
p_comb_score <- tibble(pred = feats_mat_comb_df$pred, y = feats_mat_comb_df$dAB) %>% 
    mutate(col = densCols(., bandwidth=0.06,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=pred, y=y, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() + 
        coord_cartesian(xlim = c(-1.1, 0.6), ylim = c(-1.8, 1.2)) +                 
        xlab("Combined model") + 
        ylab("Meth (3a-/-) - (3b-/-)") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("R^2 = {cor}", cor = round(cor(feats_mat_comb_df$pred, feats_mat_comb_df$dAB)^2, digits=2))) + 
        theme(plot.subtitle = ggtext::element_markdown())


p_comb_score
cor(feats_mat_comb_df$dAB, feats_mat_comb_df$pred)^2
```

```{r}
df <- gextract.left_join("DNMT.ab_score_xgb_plus", intervals=feats_mat_comb_df, iterator=feats_mat_comb_df) %>% select(comb_score = pred, dinuc_score = DNMT.ab_score_xgb_plus, dAB) %>% as_tibble()
```

```{r}
df %>%
        filter(abs(dAB) <= 0.05 )  %>%
        ggplot(aes(x=comb_score, y=dinuc_score)) +
            scattermore::geom_scattermore() + 
            geom_abline(linetype="dashed") + 
            theme(aspect.ratio=1)
```

```{r}
p_comb_vs_dinuc <- df %>% 
    mutate(col = densCols(., bandwidth=0.06,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=comb_score, y=dinuc_score, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() + 
        coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1)) +                 
        xlab("Combined model") + 
        ylab("Dinuc score") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("R^2 = {cor}", cor = round(cor(df$comb_score, df$dinuc_score)^2, digits=2))) + 
        theme(plot.subtitle = ggtext::element_markdown())


p_comb_vs_dinuc
cor(df$comb_score, df$dinuc_score)^2
```

Extract sequence from model

```{r}
flank_bp <- 5
seq_df_wide <- get_seq_df(feats_mat_comb_df %>% select(chrom, start, end), flank_bp =  flank_bp) %>% seq_df_to_wide(flank_bp = flank_bp)
```

```{r}
model_glm_comb <- gen_seq_model(seq_df_wide, feats_mat_comb_df, pred) 
```

```{r}
coef_df_comb <- get_coef_df(model_glm_comb)
```

```{r}
options(repr.plot.width = 5, repr.plot.height = 6)
p <- coef_df_comb %>% 
    ggplot(aes(x=pos, y=dinuc, fill=coefficient)) + 
        geom_tile() + 
        scale_fill_gradient2(low = "darkblue", high = "darkred", mid = "white", midpoint = 0, na.value="white") + 
        theme_minimal() + 
        ylab("Dinucleotide") + 
        xlab("Position")
p
```

### Figure 5I

```{r}
model_ab <- readr::read_rds(here("output/ab_dinuc_model_5bp.rds"))
```

```{r}
coef_df_ab <- get_coef_df(model_ab)
```

```{r}
options(repr.plot.width = 5, repr.plot.height = 6)

df <- coef_df_comb %>% 
    select(pos, dinuc, coef_comb = coefficient) %>% 
    left_join(coef_df_ab %>% rename(coef = coefficient)) %>% 
    replace_na(replace = list(coef = 0, coef_comb = 0)) %>% 
    mutate(label = paste0(pos, ",", dinuc))

df_scale <- df %>% 
    mutate_at(vars(coef, coef_comb), function(x) x - mean(x) ) %>% 
    mutate_at(vars(coef, coef_comb), function(x) x / sd(x) ) 

p <-  df %>% 
    ggplot(aes(x=coef, y=coef_comb, label=label)) + 
        geom_point() +        
        geom_abline(linetype="dashed") + 
        theme_bw() + 
        theme(aspect.ratio=1) 
              
p_scale <- df_scale %>% 
    ggplot(aes(x=coef, y=coef_comb, label=label)) + 
        geom_point(size=0.01) +        
        geom_abline(linetype="dashed") + 
        xlab("Dinuc model") + 
        ylab("Combined model") + 
        theme(aspect.ratio=1) 

cor.test(df$coef, df$coef_comb, method="spearman")

p               
p_scale
p_scale + ggrepel::geom_text_repel() 
```

### Figure 5J

```{r}
epi6 <- fread(here("output/meissner_epi_cpg_meth_sum.tsv")) %>% 
    mutate(dAB_epi6 = ko3a - ko3b, dA_epi6 = ko3a - wt, dB_epi6 = ko3b - wt) %>% 
    filter(!is.na(dAB_epi6)) %>% 
    select(chrom, start, end, wt, ko3a, ko3b, dAB_epi6, dA_epi6, dB_epi6) %>% 
    as_tibble()
nrow(epi6)
```

```{r}
epi6_scores <- gextract.left_join(c("DNMT.ab_score_comb", "DNMT.ab_score_xgb_plus"), intervals=epi6, iterator=epi6, colnames=c("comb_model", "eb_model")) %>%
    select(-(chrom1:end1)) %>%
    as_tibble()
```

```{r}
p_epi6_score <- epi6_scores %>% 
    select(eb_model, dAB_epi6) %>%
    mutate(col = densCols(., bandwidth=bandwidth,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=eb_model, y=dAB_epi6, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() + 
        coord_cartesian(xlim = c(-1, 0.6), ylim = c(-0.4, 0.6)) +         
        xlab("EB model") + 
        ylab("Epi (3a-/-) – (3b-/-)") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("r = {cor}", cor = round(cor(epi6_scores$dAB_epi6, epi6_scores$eb_model), digits=2)))
cor(epi6_scores$dAB_epi6, epi6_scores$eb_model)
p_epi6_score
```

```{r}
p_epi6_score_comb <- epi6_scores %>% 
    select(comb_model, dAB_epi6) %>%
    mutate(col = densCols(., bandwidth=bandwidth,colramp=colorRampPalette(c("white","lightblue", "blue", "darkblue", "yellow", "gold","orange","red", "darkred" )))) %>% 
    ggplot(aes(x=comb_model, y=dAB_epi6, col=col)) + 
        geom_point(shape=19, size=point_size) + 
        scale_color_identity() + 
#         coord_cartesian(xlim = c(-1, 0.6), ylim = c(-0.4, 0.6)) +         
        xlab("Comb model") + 
        ylab("Epi (3a-/-) – (3b-/-)") +         
        theme(aspect.ratio=1, panel.grid.major=element_blank(), panel.grid.minor=element_blank()) + 
        labs(subtitle = glue("r = {cor}", cor = round(cor(epi6_scores$dAB_epi6, epi6_scores$comb_model), digits=2)))
cor(epi6_scores$dAB_epi6, epi6_scores$comb_model)
p_epi6_score_comb
```
